### ISSUE TITLE
Status of the repository?

### ISSUE THREAD

**Issue by thufschmitt** [NixOS/nixops-aws#161]
Hi,

As part of https://github.com/NixOS/teams-collaboration/issues/1, I am trying to clarify the status of the repositories under the NixOS organisation.

This repository seems to be unmaintained or obsolete, so it will be archived in a month.

If you think it warrants staying here or should be moved to another organization instead, please answer this issue.

**Comment by roberth** [comment]
This repository is still maintained. The last two years' PRs weren't many, but they were all merged: https://github.com/NixOS/nixops-aws/pulls?q=is%3Apr+is%3Aclosed.
It is not obsolete. It works, and it does not have an alternative to succeed it.
