### ISSUE TITLE
Unable to create an s3 bucket in the EU

### ISSUE THREAD

**Issue by NorfairKing** [NixOS/nixops-aws#88]
I'm trying to create an s3 bucket like this:
```
      s3Buckets.backupBucket = {
        name = "backup";
        versioning = "Suspended";
        inherit region;
        inherit accessKeyId;
      };
```

And I get: 
```
botocore.exceptions.ClientError: An error occurred (IllegalLocationConstraintException) when calling the CreateBucket operation: The EU location constraint is incompatible for the region specific endpoint this request was sent to.
```
More of an explanation here:
https://github.com/aws/aws-cli/issues/2603

and here:

https://docs.aws.amazon.com/cli/latest/reference/s3api/create-bucket.html
> The following command creates a bucket named my-bucket in the eu-west-1 region. Regions outside of us-east-1 require the appropriate LocationConstraint to be specified in order to create the bucket in the desired region:

**Comment by tewfik-ghariani** [comment]
This could actually be related to the misleading error message from AWS as explained here 

>Bucket names are GLOBALLY unique! AWS CLI will give you the **IllegalLocationConstraintException** if you collide with an already existing bucket and you've specified a region different than the region of the already existing bucket. If you happen to guess the correct region of the existing bucket it will give you the `BucketAlreadyExists` exception.

https://github.com/aws/aws-cli/issues/2603#issuecomment-428220985

`backup` bucket is surely not unique on a global scale and it must have been created in a different region

Can you try to create a bucket in _eu-west-1_ with a different name satisfying the requirements stated by AWS https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html#bucketnamingrules

**Comment by NorfairKing** [comment]
Pretty sure that this was my fault afteral, closing.
