### ISSUE TITLE
Impossible to use this plugin locally

### ISSUE THREAD

**Issue by RaitoBezarius** [NixOS/nixops-aws#9]
Due to the fact that `release.nix` uses a variable called `src`, I am not sure why but it causes issues during the `./dev-shell --arg p "[ p.callPackage ../nixops-aws/release.nix {}]"`, thus making very difficult to work locally on this plugin.

If changed to `awsSrc` in the top level, it works, I'm not a specialist of Nix but it'd be good to understand why this happens.

**Comment by AmineChikhaoui** [comment]
@edolstra I partially reverted 0af9c8b as it broke the current process of running ./dev-shell with a local checkout of the AWS plugin.
